# Generated by Django 6.0 on 2025-12-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='Nombre del sitio')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logos/', verbose_name='Logo del sitio')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='site/images/', verbose_name='Portada del sitio')),
                ('site_description', models.CharField(max_length=500, verbose_name='Descripción del sitio')),
                ('google_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site Tag Google')),
                ('facebook_pixel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pixel de Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Información del Sitio',
                'verbose_name_plural': 'Información del Sitio',
                'ordering': ['updated_at'],
            },
        ),
    ]
