# Generated by Django 6.0.4 on 2026-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50, verbose_name='Nombre de invitado')),
                ('companion_name', models.CharField(max_length=50, verbose_name='Nombre del acompañante')),
                ('total_guests', models.IntegerField(max_length=1, verbose_name='Total de invitados')),
                ('slug', models.URLField(max_length=75, verbose_name='URI identificador')),
                ('status', models.CharField(choices=[('sin-confirmar', 'Sin Confirmar'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='sin-confirmar', max_length=25, verbose_name='Stats')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['guest_name'],
            },
        ),
    ]
