# Generated by Django 6.0.4 on 2026-05-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='table',
            field=models.CharField(default=None, max_length=50, verbose_name='Mesa'),
        ),
    ]
