# Generated by Django 6.0.4 on 2026-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_guest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='slug',
            field=models.SlugField(max_length=75, verbose_name='URI identificador'),
        ),
    ]
